version: '3.9'

services:
  web:
    build: .
    command: python /django_bookstore/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_bookstore
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-o-!xf)2kmfuedw&t*5zfr7(j+^tnm)9c)h7$$9z7x+it!#9sacb"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
